apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: thaqif101/app:latest
        ports:
        - containerPort: 5010
        env:
        - name: DATA_CLEANING_URL
          value: "http://host.docker.internal:5001"
        - name: DATA_MODELLING_URL
          value: "http://host.docker.internal:5002"
        - name: DATA_INPUT_URL
          value: "http://host.docker.internal:5000"

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5010
  type: LoadBalancer
