# Use official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory
WORKDIR /data_cleaning

# Copy the requirements file and install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the necessary Python files for data cleaning
COPY src/data_cleaning.py .

# Expose port (if required for a web service)
EXPOSE 5001

# Command to run the application (adjust as needed)
CMD ["python", "data_cleaning.py"]
