FROM python:3.9-slim

WORKDIR /data_modelling

# Install system dependencies, including libgomp1 and compilers
RUN apt-get update && apt-get install -y \
    libgomp1 \
    gcc \
    g++ \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy and install Python dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the script
COPY src/data_modelling.py ./

EXPOSE 5002

CMD ["python", "data_modelling.py"]
