# Use a lightweight Python image
FROM python:3.9-slim

# Set working directory
WORKDIR /data_input

# Copy dependencies file first
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY src/data_input.py .

# Expose the correct port
EXPOSE 5000

# Run the application
CMD ["python", "data_input.py"]
