apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: thaqif101/app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5010
        env:
        - name: DATA_CLEANING_URL
          value: "http://data-cleaning-service:5001"
        - name: DATA_MODELLING_URL
          value: "http://data-modelling-service:5002"
        - name: DATA_INPUT_URL
          value: "http://data-input-service:5000"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://grafana-k8s-monitoring-alloy-receiver.default.svc.cluster.local:4317"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://grafana-k8s-monitoring-alloy-receiver.default.svc.cluster.local:4318"
        - name: OTEL_EXPORTER_ZIPKIN_ENDPOINT
          value: "http://grafana-k8s-monitoring-alloy-receiver.default.svc.cluster.local:9411"
        - name: OTEL_SERVICE_NAME
          value: "app-monitor-service"
        volumeMounts:
        - name: model-storage
          mountPath: "/mnt/models"  # Inside container
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 5010
      targetPort: 5010
  type: LoadBalancer
