apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-modelling-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-modelling
  template:
    metadata:
      labels:
        app: data-modelling
    spec:
      containers:
      - name: data-modelling
        image: terenceyew/data-modelling:latest
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: data-modelling-service
spec:
  selector:
    app: data-modelling
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
  type: ClusterIP
