apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-cleaning-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-cleaning
  template:
    metadata:
      labels:
        app: data-cleaning
    spec:
      containers:
      - name: data-cleaning
        image: terenceyew/data-cleaning:latest
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: data-cleaning-service
spec:
  selector:
    app: data-cleaning
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP
