# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: data-input-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: data-input
#   template:
#     metadata:
#       labels:
#         app: data-input
#     spec:
#       containers:
#       - name: data-input
#         image: pitzaheart/data-input-image:latest
#         ports:
#         - containerPort: 5000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: data-input-service
# spec:
#   selector:
#     app: data-input
#   ports:
#   - protocol: TCP
#     port: 5000
#     targetPort: 5000
#     nodePort: 30007  # Optional: specify a custom port (30000-32767)
#   type: NodePort


apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-input-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-input
  template:
    metadata:
      labels:
        app: data-input
    spec:
      containers:
      - name: data-input
        image: pitzaheart/data-input-image:latest
        command: ["python", "data_input.py"]   # Ensure this is the command to run your script
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: data-input-service
spec:
  selector:
    app: data-input
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
